image: node:6

before_script:
  - npm prune
  - npm i --no-optional

cache:
  key: "$CI_BUILD_REF_NAME"
  paths:
    - node_modules/
    - lib/

stages:
  - build
  - test

"Compile with Babel":
  stage: build
  script: npm run build

"Test:Lint":
  variables:
    TEST_TYPE: lint
  stage: test
  script: node bin/ci.js

"Test:Create Project":
  variables:
    TEST_TYPE: test_create_project
  stage: test
  script: node bin/ci.js
